Fixed sitemap using relative urls & fix: styles of ul, li and code blocks improved (production)
cfengine/cfbs-web pull request #143
Opened 2024-01-25 14:41 UTC by aleksandrychev

2024-01-25 15:30 UTC, olehermanse commented
@mineralsfree @aleksandrychev Please take a look here:

https://staging.build.cfengine.com/modules/packages-allowlist-snapshot/

Looks like something is going wrong with the code block.

2024-01-25 17:30 UTC, aleksandrychev commented
> @mineralsfree @aleksandrychev Please take a look here:
> 
> https://staging.build.cfengine.com/modules/packages-allowlist-snapshot/
> 
> Looks like something is going wrong with the code block.

this change seems like intended to be applied only to normal code blocks, not highlighted ones https://github.com/cfengine/build-website/pull/143/files#diff-dde5e13bafad3fc8007de43f016ee5b7c60c262bac09ba7643043726a3e39c84R252-R257

2024-01-29 19:54 UTC, olehermanse requested changes
Waiting for code block fix from @mineralsfree

2024-02-01 12:51 UTC, olehermanse approved these changes

2024-02-01 12:51 UTC, merged